### ISSUE TITLE
pressure issue with PGN 130310 and 130311

### ISSUE THREAD

**Issue by usauerbrey** [ttlappalainen/NMEA2000#18]
In N2kMessages.h at the PGNs 130310 and 130311 the comment says "AtmosphericPressure   Atmospheric pressure in Pascals. Use function mBarToPascal, if you like to use mBar"
But when I feed 1234.5 mBar with mBarToPascal the result on Raymarine i70 is 14964 and in Actisense NMEA Reader 5791400 pascal.
When I do not use the mBarToPascal-conversion, everythink looks fine. i70 show 1235 and in NMEA Reader say 123500 pascal.
Is the comment wrong?
please clearify.

Thanks Uwe

**Comment by ttlappalainen** [comment]
Code seem to be wrong. Point was to use SI-units and related conversion routines. So you should have
    N2kMsg.Add2ByteUDouble(AtmosphericPressure,100);
in SetN2kPGN130310 in N2kMessages.cpp
I have other updates under testing, so I'll fix that on next update.

**Comment by sarfata** [comment]
I am not sure I understand this.

In KBox, I store values in Pascal internally (in the BarometerMeasurement
class) and send them as is to PGN 130311 and it works well on my i70:

https://github.com/sarfata/kbox-firmware/blob/master/lib/KBox/src/converters/BarometerN2kConverter.cpp

And:
https://github.com/sarfata/kbox-firmware/blob/master/lib/KBox/src/tasks/BarometerTask.cpp

So for me, it seems to work as documented.

Thomas

On Aug 13, 2016 11:55 PM, "ttlappalainen" <notifications@github.com> wrote:

Code seem to be wrong. Point was to use SI-units and related conversion
routines. So you should have
N2kMsg.Add2ByteUDouble(AtmosphericPressure,100);
in SetN2kPGN130310 in N2kMessages.cpp
I have other updates under testing, so I'll fix that on next update.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ttlappalainen/NMEA2000/issues/18#issuecomment-239659131>,
or mute the thread

**Comment by ttlappalainen** [comment]
Thomas is right. I looked wrong for my last response. I tested code as it is and changed line on example MessageSender:
SetN2kOutsideEnvironmentalParameters(N2kMsg, 1, ReadWaterTemp(), CToKelvin(25.3), mBarToPascal(1013.5));
and NMEAReader shows me 101400 Pascal

**Comment by ttlappalainen** [comment]
Sorry for messing, it it too late to test anything. I already made the correction for the library and tested it with that. So it is as my first response. Thomas: you read pressure in pascals, but then you create:
BarometerMeasurement m(temperature, pressure / 100); 
meaning you have converted it to mBar (or hPA). And as my document says, it expect values as PA (Pascal).

**Comment by ttlappalainen** [comment]
I just updated the library to use Pascal unist, so now you have to use mBarToPascal!

**Comment by sarfata** [comment]
@ttlappalainen I think you can close this issue. There is no issue :)
