### ISSUE TITLE
Try to send both Apparent and True wind 

### ISSUE THREAD

**Issue by PeppeCa** [ttlappalainen/NMEA2000#252]
Hi to everybody,
First, thank you for your time.
I am replacing my ITC-5 with and Arduino DUE and a MCP2562 and I am using the library of [ttlappalainen](https://github.com/ttlappalainen) (thanks a lot!).
I want to send both the apparent wind and the true wind to bus and I am using the two command below:

SetN2kWindSpeed(N2kMsg, 1, ReadWindSpeed(), ReadWindAngle(),N2kWind_Apprent);
SetN2kWindSpeed(N2kMsg, 2, TWSfunc(), TWAfunc(), N2kWind_True_North);

However, it seems that the second line overwrites the first. I tested it with a NMEA reader and a signalK server
Is there something wrong in my thinking?
I need to use two different devices?

**Comment by ttlappalainen** [comment]
You need to do.

SetN2kWindSpeed(N2kMsg, 1, ReadWindSpeed(), ReadWindAngle(),N2kWind_Apprent);
NMEA2000.SentMsg(N2kMsg);
SetN2kWindSpeed(N2kMsg, 2, TWSfunc(), TWAfunc(), N2kWind_True_North);
NMEA2000.SentMsg(N2kMsg);

If you do not really handle SID, use 0xff for them. SID marks that measurement has been done at same time so that handler can treat then measured same time even messages may arrive at different times. And on every new send you should increment SID.

**Comment by PeppeCa** [comment]
I don't understand what you mean. I use the two function below and they seem near your code:
_void SendN2kWind() {
  static unsigned long WindUpdated=millis();
  tN2kMsg N2kMsg;

  if ( WindUpdated+WindUpdatePeriod<millis() ) {
    SetN2kWindSpeed(N2kMsg, 1, ReadWindSpeed(), ReadWindAngle(),N2kWind_Apprent);
    WindUpdated=millis();
    NMEA2000.SendMsg(N2kMsg);
  }
}
void SendN2kWindT() {
  static unsigned long WindUpdated=millis();
  tN2kMsg N2kMsg;

  if ( WindUpdated+WindUpdatePeriod<millis() ) {
    SetN2kWindSpeed(N2kMsg, 2, TWSfunc(), TWAfunc(), N2kWind_True_North);
    WindUpdated=millis();
    NMEA2000.SendMsg(N2kMsg);
  }
}_
